# Generated by Django 4.0.4 on 2022-04-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'admin'), (100, 'branch1'), (101, 'branch2'), (102, 'branch3')], null=True),
        ),
    ]
