# Generated by Django 4.0.4 on 2022-04-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0002_alter_user_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='branchCode',
            field=models.PositiveSmallIntegerField(choices=[(101, '101'), (102, '102'), (103, '103')]),
        ),
    ]
