# Generated by Django 4.0.4 on 2022-04-13 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0003_alter_data_branchcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='dateAndTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='branchCode',
            field=models.PositiveSmallIntegerField(choices=[(100, '100'), (101, '101'), (102, '102')]),
        ),
    ]
